# Airflow Pod가 특정 노드에 배치되도록 지정합니다.
nodeSelector:
  agentpool: default

# Airflow Executor 설정
executor: 'KubernetesExecutor'

# 모든 Airflow 컨테이너에 대한 환경 변수
env:
  - name: ENVIRONMENT
    value: dev

# 추가 환경 변수 설정
extraEnv: |
  - name: AIRFLOW__CORE__DEFAULT_TIMEZONE
    value: 'Asia/Seoul'  # 한국 표준 시간대 설정

# Airflow 설정 파일을 수정합니다.
postgresql:
  enabled: true

# Pgbouncer 활성화 설정
# 자세한 내용은 https://airflow.apache.org/docs/helm-chart/stable/production-guide.html#pgbouncer 참조
pgbouncer:
  enabled: true

logs:
  persistence:
    enabled: true
    existingClaim: pvc-airflow-logs
    storageClassName: azureblob-fuse-premium

# We disable the log groomer sidecar because we use Azure Blob Storage for logs,
# where a lifecycle policy is already set
triggerer:
  logGroomerSidecar:
    enabled: false

scheduler:
  logGroomerSidecar:
    enabled: false

workers:
  logGroomerSidecar:
    enabled: false

dags:
  gitSync:
    enabled: true
    repo: git@github.com:StatisticsFox/AKS-DAG-tset.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: 'dags'
    sshKeySecret: airflow-git-ssh-secret
    knownHosts: |
      github.com ssh-rsa <github.com public key>